name: Run Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable universe repository
        run: |
          sudo add-apt-repository universe
          sudo apt-get update

      - name: Install Chrome dependencies
        run: |
          sudo apt-get install -y wget curl unzip fonts-liberation libappindicator3-1 libatk-bridge2.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libnss3 libxcomposite1 libxcursor1 libxi6 libxrandr2 libxss1 libxtst6

      - name: Install Chrome and ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Check Chrome and ChromeDriver Versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}
          ADDRESS: ${{ secrets.ADDRESS }}
          CITY: ${{ secrets.CITY }}
          ZIP_CODE: ${{ secrets.ZIP_CODE }}
          PHONE: ${{ secrets.PHONE }}
          STATE: ${{ secrets.STATE }}
          STATE_INDEX: ${{ secrets.STATE_INDEX }}
        run: |
          python formtest.py