name: Run Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Google Chrome and ChromeDriver
        uses: actions/setup-chrome@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}
          ADDRESS: ${{ secrets.ADDRESS }}
          CITY: ${{ secrets.CITY }}
          ZIP_CODE: ${{ secrets.ZIP_CODE }}
          PHONE: ${{ secrets.PHONE }}
          STATE: ${{ secrets.STATE }}
          STATE_INDEX: ${{ secrets.STATE_INDEX }}
        run: |
          python formtest.py