name: Run Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Chrome and ChromeDriver
        run: |
          # Install Google Chrome
          sudo apt-get update -qq
          sudo apt-get install -y wget curl unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libnss3 libxcomposite1 libxcursor1 libxi6 libxrandr2 libxss1 libxtst6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller

      - name: Run script
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}
          ADDRESS: ${{ secrets.ADDRESS }}
          CITY: ${{ secrets.CITY }}
          ZIP_CODE: ${{ secrets.ZIP_CODE }}
          PHONE: ${{ secrets.PHONE }}
          STATE: ${{ secrets.STATE }}
          STATE_INDEX: ${{ secrets.STATE_INDEX }}
        run: |
          python formtest.py